import test from 'node:test';
import assert from 'node:assert/strict';
import {
  normalizeCard, normalizeInstallmentPlan, projectInstallments, calculateSafeAvailable,
  simulateNewPurchase, simulatePlanPayoff, calculateCostToFreeOneMonthlyPeso, getReleasedFlowBetween
} from '../utils/planningEngine.js';

const plan=(overrides={})=>({id:'p1',owner:'yair',cardId:'a',description:'Compra',originalAmount:1186.55,remainingBalance:988.79,installmentAmount:197.76,totalInstallments:6,currentInstallment:1,remainingInstallments:5,interestType:'none',active:true,ownershipType:'personal',ownerSharePercentage:100,...overrides});

test('MSI 1/6 genera cinco pagos futuros y libera flujo después del último',()=>{ const rows=projectInstallments([plan()],{startMonth:'2026-09',months:7}); assert.deepEqual(rows.map(r=>r.totalCommitment),[197.76,197.76,197.76,197.76,197.76,0,0]); assert.equal(rows[4].endingPlans.length,1); assert.equal(rows[4].releasedFlow,0); assert.equal(rows[5].releasedFlow,197.76); });
test('MSI 11/12 mantiene el último mes comprometido y libera en el posterior',()=>{ const rows=projectInstallments([plan({totalInstallments:12,currentInstallment:11,remainingInstallments:1,installmentAmount:440})],{startMonth:'2026-09',months:3}); assert.equal(rows[0].totalCommitment,440); assert.equal(rows[0].endingPlans[0].id,'p1'); assert.equal(rows[0].releasedFlow,0); assert.equal(rows[1].totalCommitment,0); assert.equal(rows[1].releasedFlow,440); });
test('MSI 1/3 paga dos meses, termina en el segundo y libera en el tercero',()=>{ const rows=projectInstallments([plan({totalInstallments:3,currentInstallment:1,remainingInstallments:2,installmentAmount:133})],{startMonth:'2026-09',months:3}); assert.equal(rows[0].totalCommitment,133); assert.equal(rows[1].totalCommitment,133); assert.equal(rows[1].endingPlans[0].id,'p1'); assert.equal(rows[1].releasedFlow,0); assert.equal(rows[2].releasedFlow,133); });
test('MSI 3/3 no genera pagos',()=>assert.ok(projectInstallments([plan({totalInstallments:3,currentInstallment:3,remainingInstallments:0})],{months:3}).every(r=>r.totalCommitment===0)));
test('compra compartida 50/50 conserva deuda household y libera sólo la parte efectiva',()=>{ const rows=projectInstallments([plan({installmentAmount:1000,remainingInstallments:1,ownershipType:'shared',ownerSharePercentage:50})],{months:2}); assert.equal(rows[0].householdCommitment,1000); assert.equal(rows[0].effectiveCommitment,500); assert.equal(rows[0].releasedFlow,0); assert.equal(rows[1].releasedFlow,500); });
test('compra personal conserva 100%',()=>assert.equal(projectInstallments([plan({installmentAmount:823.23})],{months:1})[0].effectiveCommitment,823.23));
test('se distinguen MSI e interés',()=>{ const rows=projectInstallments([plan({remainingInstallments:1}),plan({id:'p2',interestType:'interest',installmentAmount:208.95,remainingInstallments:2})],{startMonth:'2026-09',months:3}); assert.equal(rows[0].msiCommitment,197.76); assert.equal(rows[0].interestCommitment,208.95); });
test('getReleasedFlowBetween cuenta sólo meses posteriores al último pago',()=>{ const rows=projectInstallments([plan({remainingInstallments:1}),plan({id:'p2',interestType:'interest',installmentAmount:208.95,remainingInstallments:2})],{startMonth:'2026-09',months:4}); assert.equal(getReleasedFlowBetween(rows,'2026-09','2026-09'),0); assert.equal(getReleasedFlowBetween(rows,'2026-10','2026-10'),197.76); assert.equal(getReleasedFlowBetween(rows,'2026-10','2026-11'),406.71); });
test('simular compra no muta planes y cambia proyección temporal',()=>{ const plans=[plan()]; const snapshot=structuredClone(plans); const result=simulateNewPurchase(plans,{amount:12000,totalInstallments:12,ownershipType:'personal'},{months:12}); assert.deepEqual(plans,snapshot); assert.equal(result.plan.installmentAmount,1000); assert.equal(result.after[0].effectiveCommitment-result.before[0].effectiveCommitment,1000); });
test('compra simulada libera después de pagar y queda fuera si termina en el horizonte',()=>{ const within=simulateNewPurchase([],{amount:300,totalInstallments:2},{startMonth:'2026-09',months:3}); assert.equal(within.after[1].endingPlans.length,1); assert.equal(within.after[1].releasedFlow,0); assert.equal(within.after[2].releasedFlow,150); const outside=simulateNewPurchase([],{amount:1200,totalInstallments:12},{startMonth:'2026-09',months:12}); assert.ok(outside.after.every(row=>row.releasedFlow===0)); });
test('liquidación hipotética no muta y elimina su proyección',()=>{ const plans=[plan()]; const result=simulatePlanPayoff(plans,'p1',{months:2}); assert.equal(result.before[0].totalCommitment,197.76); assert.equal(result.after[0].totalCommitment,0); assert.equal(plans[0].active,true); assert.match(result.warning,/banco/); });
test('tarjeta legacy se normaliza sin romper aliases',()=>{ const card=normalizeCard({name:'Legacy',limit:10000,balance:123,cutDay:5,payDay:20}); assert.equal(card.creditLimit,10000); assert.equal(card.currentBalance,123); assert.equal(card.type,'credit'); assert.equal(card.active,true); });
test('dinero usa centavos y evita 0.1 + 0.2',()=>{ const row=projectInstallments([plan({id:'a',installmentAmount:.1}),plan({id:'b',installmentAmount:.2})],{months:1})[0]; assert.equal(row.totalCommitment,.3); });
test('disponible seguro reporta faltantes y descuenta objetivo',()=>{ assert.ok(calculateSafeAvailable({incomeAvailable:100}).missing.includes('fixedExpenses')); assert.deepEqual(calculateSafeAvailable({incomeAvailable:10000,fixedExpenses:2000,currentSpending:1000,currentCardPayments:500,goalsReserved:500,buffer:1000,nextInstallments:1000,reductionTarget:1500}),{availableSafeMonth:2500,availableSafeWeek:625,missing:[]}); });
test('normalización y costo para liberar flujo',()=>{ const p=normalizeInstallmentPlan(plan({remainingBalance:1000,installmentAmount:250})); assert.equal(calculateCostToFreeOneMonthlyPeso(p),4); });

test('fixture representativo separa deuda household y participación personal', async()=>{ const { representativePlanningPlans }=await import('./fixtures/planningPlans.mjs'); const row=projectInstallments(representativePlanningPlans,{months:1})[0]; assert.equal(row.householdCommitment,266.33); assert.equal(row.effectiveCommitment,2828.45); assert.equal(row.interestCommitment,208.95); });
